### ISSUE TITLE
awesome-list compliance?

### ISSUE THREAD

**Issue by d-wasserman** [APA-Technology-Division/urban-and-regional-planning-resources#14]
I am curious if we should make changes to the repo to comply with the [awesome-list](https://github.com/sindresorhus/awesome/blob/main/create-list.md) standards. My understanding is that this would require:

- [x] Repo formatting changes (hierarchical changes?)
- [x] Add awesome badge
- [x] Add Table of Contents
- [x] Branch name change
- [x] CC0 License
- [x] Add code of conduct
- [x] Change pull requests responses moving forward or past ones.
- [x] Get acknowledged into the awesome-list.

**Comment by Jogai** [comment]
To me awesome-urban-planning is a lot better. I dont know anything about urban planning, but at least I can guess whats it about by the title. "planning-technology-resources" would be a far broader topic (and the reason I initially opened the issue you submitted on the awesome list).

I believe that github automatically redirects repo names when you rename a repo.

Removing details seems like a step back, unless that info was already too extensive. What you could do too is make a companion repo formatted as an awesome list. There you link to this repo mentioning that its a bit different but more extensive. The only challenge then is to keep both lists in 'sync' as listed awesome list could potentially attract more contributors.

**Comment by d-wasserman** [comment]
I am starting to think that would align more with the intent of the repo. We need to balance APA's expectations of the division and compliance with what would be the best for for the awesome list (we are one division of a [multidisciplinary set of technical divisions](https://planning.org/divisions/), and there might be concerns that we are "speaking" for all of them - this is likely an overblown concern). 

I am mostly concerned of if we use the name space again (on accident), I think it stops the redirect. That said, the more I think about it for this organization that is unlikely. 

I think we might already have too much detail? I think the license provides a lot of value, but ideally a live link removes the need to state a provider (unless the link dies, then the provider is really important). Do you think awesome-list would reject the hierarchal readme set up we have or is that not pertinent to the standard?

**Comment by Jogai** [comment]
I dont think the hierarchy is a problem. Just try to incorporate it into the main readme. 

Regarding licence/provider; some repo's use icons in the list to show licences, and maybe the provider can be displayed in brackets. If its small enough I dont think thats a problem for the awesome standard.

**Comment by d-wasserman** [comment]
We can simplify our contribution format based on this feedback and keep the hierarchy. That is feasible.

**Comment by d-wasserman** [comment]
We emailed the manager of the repo and have determined that renaming the repo is recommended but not required. We will proceed with other compliance items.

**Comment by d-wasserman** [comment]
✖  1:1  Invalid URL: ./resource_pages/PublicDataResources.md  remark-lint:double-link
  ✖  1:1  Missing Awesome badge after the main heading          remark-lint:awesome-badge
  ✖  1:1  Missing or invalid Table of Contents                  remark-lint:awesome-toc
These are the last items we need to add or change to the repo for compliance. I am going to run this by the executive committee  this week.

**Comment by d-wasserman** [comment]
The current checks we are failing are related to the hierarchal nature of our TOC. Many awesome-lists are one one page, but we link to other pages. 
  ✖  1:1  Invalid URL: ./resource_pages/PublicDataResources.md  remark-lint:double-link
  ✖  1:1  Missing or invalid Table of Contents                  remark-lint:awesome-toc
This is a moderate amount of effort to change, but I want a ruling on our PR before we make the change.

**Comment by d-wasserman** [comment]
With #20 , this is largely resolved. We are using a flag to ignore a TOC error that seems to incredibly minor. I think we will need to come back to this, but with a future issue. We have an active actions workflow to monitor new PRs with awesome-lint, but the TOC will require attention manually till we resolve the exact issues with it. This might be done in a future dev branch. This is closed for now. While a burdensome process, I think the repo is better for it.

**Comment by d-wasserman** [comment]
@lianplass, @colemant , @rpnathansonstl - 
The awesome-list submission is getting attention, and one of the things I think we might want to do is rename this repo to be more clear. I was thinking we rename this report to "urban-and-regional-planning-resources". What does everyone think about this? 
See discussion here:
https://github.com/sindresorhus/awesome/pull/2013

**Comment by colemant** [comment]
urban-and-regional-planning-resources  sounds great

great job everyone

**Comment by d-wasserman** [comment]
Awesome. I am renaming the repo. We need to fix the URLs next.

**Comment by d-wasserman** [comment]
Added into awesome repo. Closing.
