### ISSUE TITLE
Climate Change Resources

### ISSUE THREAD

**Issue by d-wasserman** [APA-Technology-Division/urban-and-regional-planning-resources#25]
There are a few tools in this Report on[ Climate Change Planning Tools](https://www.tpl.org/decision-support-tools-climate-change-planning) that make me wonder if we should have a separate call out for Climate related software and platforms/data sources. For example, we have Resilience & Natural Hazards. I think Climate is distinct enough to get separate sub-categories right? 

PS, can someone help get some of these out the appendix into the repo?

**Comment by lianplass** [comment]
Hi David,

I agree that these resources would be of value.  Would it be possible to create subcategories of resources for various climate impacts (e.g.,  impact measurement tools, temperature, weather events,  water  etc.) or should we apply strict parameters to this category?

Here are a few tools/resources I have used/encountered over the course of my work (not sorted):

**NOAA Climate Impact Data**
[Link](https://www.climate.gov/maps-data)

**NOAA Extreme Weather Events GIS Data**
[Link](https://www.ncdc.noaa.gov/data-access/severe-weather)

**UN Sustainable Development Solutions Network**
[Link](https://www.unsdsn.org/sdg-index-and-monitoring)

**ICLEI Clearpath**
[Link](https://icleiusa.org/clearpath/)

**ICLEI Temperate**
[Link](https://icleiusa.org/temperate-adaptation-planner/)

**NREL Solar Radiation Data**
[Link](https://nsrdb.nrel.gov/)

**FEMA Flood Map Service Center**
https://msc.fema.gov/portal/home

Happy to help develop this cache of resources.

**Comment by d-wasserman** [comment]
Some of these are already in here in some form (or could augment an entry - like the FEMA Map center), and some are vendors. I think these are all worth contributions, but we want to do PR's for them a category at  a time.

**Comment by d-wasserman** [comment]
@lianplass , I contributed a significant portion of the ones listed here. I am curious if the solutions network belongs in a new category entirely. Not sure if we have NREL added yet.

**Comment by d-wasserman** [comment]
Closing this issue for now in preparation of Hactoberfest.
