### ISSUE TITLE
AICP or Educational Resources

### ISSUE THREAD

**Issue by c-goodman** [APA-Technology-Division/urban-and-regional-planning-resources#30]
Been doing research on taking the AICP exam recently and I realized that it would be nice to have a repository of educational/informative resources.

Haven't put much thought into it yet but perhaps this could expand into a section for educational resources to learn more about Urban Planning in general?

**Comment by d-wasserman** [comment]
I have been thinking about that too. I was thinking of a section for literature and educational research, but I feel like just NCHRP reports could fill it up if we were not careful. How about:
# Educational & Informational Resources
These are collections of planning related literature, information aggregators, or similar resources. 

Under that we would have:

## AICP Resources

**Comment by d-wasserman** [comment]
@c-goodman - do you want to submit a pull request for this change?

**Comment by c-goodman** [comment]
I will later today.

**Comment by d-wasserman** [comment]
Awesome. Between Platforms & Other resources is a good spot.

**Comment by d-wasserman** [comment]
Addressed with #31.
