### ISSUE TITLE
Graphic Edit

### ISSUE THREAD

**Issue by d-wasserman** [APA-Technology-Division/urban-and-regional-planning-resources#33]
@lianplass - can we edit this graphic to match the current name of the repo? 
https://github.com/APA-Technology-Division/urban-and-regional-planning-resources/blob/main/resources/apa_planning_tech_repoflow-02-01.png
I can take a shot at it if needed.

**Comment by lianplass** [comment]
Addressed--let me know if you need me to make any other tweaks to this!
