### ISSUE TITLE
Resources for planners learning to code

### ISSUE THREAD

**Issue by kellytdunn** [APA-Technology-Division/urban-and-regional-planning-resources#36]
Does this repo have any interest in compiling resources for planners wanting to learn to code? That could be an interesting branch, if so. I am meeting a lot of planners lately who are trying to figure out how to get started, so I've got some ideas.

**Comment by d-wasserman** [comment]
I think we could make a tag for it in the Coding Resources section. I think it would be ideal though if the tutorials were specifically oriented towards urban informatics such as Berkley's UDS classes.

**Comment by d-wasserman** [comment]
@kellytdunn , we would welcome PRs on this topic of learning if you have any suggestions.

**Comment by kellytdunn** [comment]
Thanks! I will see what I can gather.

**Comment by d-wasserman** [comment]
We are planning a hackathon in October, so don't share everything at once!

**Comment by d-wasserman** [comment]
@kellytdunn , feel free to share resources on this issue if you want any feedback.

**Comment by d-wasserman** [comment]
@kellytdunn we are going to close this issue for now. Feel free to submit PRs on this topic.
