### ISSUE TITLE
Creation of Subheader for Administrative Tools and Resources

### ISSUE THREAD

**Issue by lianplass** [APA-Technology-Division/urban-and-regional-planning-resources#60]
As the title suggests, do we want to create a new subheader specifically for tools that can be used to improve administrative workflows in local governments and planning organizations?  That might include resources <u>or even frameworks</u> that support:

- Plan review 
- Task automation
- Processing scanned documents (e.g., file conversion)
- More generally, converting files to a machine-readable format

To that end, what kind of support is available for resources that are free and open source?  Let me know your thoughts.

-Li

**Comment by d-wasserman** [comment]
I think we need to start with the materials we collected with NPC, but something we need a decision quickly on is the taxonomy. Do we group them? Do we need multiple categories?
Thoughts (question marks where  I weakly held opinions.
1. We put this in platforms. 
2. We make a "Operations, Permitting, and Development Review" subheader?
3. We rename Urban Planning Tools and Platforms to "Land Use Planning Tools & Platforms"?

**Comment by d-wasserman** [comment]
@lianplass - I think we just call it "Administrative Tools & Resources" like you said. Do we put digital plans in a separate category?

**Comment by d-wasserman** [comment]
First draft in #f7c49e07e4e219c445315eac6a95464d39f1dfc0

**Comment by d-wasserman** [comment]
Closing this for now. We might need to revisit for digital plans.
