### ISSUE TITLE
Possible Links to Inlcude

### ISSUE THREAD

**Issue by npr99** [APA-Technology-Division/urban-and-regional-planning-resources#70]
I don't have time right now to make an official change but here are some ideas:

1. Open Source Software for Working with OpenStreetMap Data https://osmcode.org/
2. National Structure Inventory - https://www.hec.usace.army.mil/confluence/nsi/technicalreferences/2022/technical-documentation

Also, just curious if I can submit an issue

**Comment by d-wasserman** [comment]
We can review it in our own time, but we prefer PRs usually one at a time so.

**Comment by d-wasserman** [comment]
I have added NSI. Need to think about how to classify osmcode. Likely OSM.
