### ISSUE TITLE
AI Tools & Platforms

### ISSUE THREAD

**Issue by d-wasserman** [APA-Technology-Division/urban-and-regional-planning-resources#73]
@APA-Technology-Division/leadership-team 
Should this be its own section or nested within the categories we have developed already? I could see it being a subsection of platforms & tools.

**Comment by lianplass** [comment]
Hi David,

Commenting now to let you know i'm owning this issue and making the update now.  Will attempt to create a branch you can merge upon review as opposed to committing to main directly.  Its harder to do this as an admin so please bear with me!

-Li

-Li

**Comment by lianplass** [comment]
See PR #75 ! @d-wasserman

**Comment by d-wasserman** [comment]
This works! Edits can come later!
