### ISSUE TITLE
Equity Datasets Gaps

### ISSUE THREAD

**Issue by d-wasserman** [APA-Technology-Division/urban-and-regional-planning-resources#74]
In advance of the next article for APA we need to add a few resources:

- [ ] https://onemap.cdc.gov/portal/apps/sites/#/eji-explorer

**Comment by lianplass** [comment]
Hi David,  

Here are a few resources i'm aware of/found:
* **USDOT Equitable Transportation Community (ETC) Explorer** - [https://experience.arcgis.com/experience/0920984aa80a4362b8778d779b090723/page/ETC-Explorer---Homepage/]
**Description:** _The U.S. DOT Equitable Transportation Community (ETC) Explorer is an interactive web application that uses 2020 Census Tracts and data, to explore the cumulative burden communities experience, as a result of underinvestment in transportation, in the following five components: Transportation Insecurity, Climate and Disaster Risk Burden, Environmental Burden, Health Vulnerability, and Social Vulnerability._ 
* **LEHD** (if not already included should probably be included in the article- [https://lehd.ces.census.gov/]
* **EPA Smart Location Database: **
  - Link 1: [https://www.epa.gov/smartgrowth/smart-location-mapping#SLD]
  - Link 2: [https://www.epa.gov/smartgrowth/smart-location-mapping]
**Description: **_The Smart Location Database is a nationwide geographic data resource for measuring location efficiency. It includes more than 90 attributes summarizing characteristics such as housing density, diversity of land use, neighborhood design, destination accessibility, transit service, employment, and demographics. Most attributes are available for every census block group in the United States._
* **EPA EJ Screen Tool** -  [https://www.epa.gov/ejscreen]
**Description:** _n order to better meet the Agency’s responsibilities related to the protection of public health and the environment, EPA has developed a new environmental justice (EJ) mapping and screening tool called EJScreen. It is based on nationally consistent data and an approach that combines environmental and demographic indicators in maps and reports. _
* **Open Trip Planner** - [https://www.opentripplanner.org/]
* **GTFS** - [https://gtfs.org/]

**Comment by d-wasserman** [comment]
I think we need to add the USDOT too, but we cover LEHD elsewhere, but it is also an equity dataset in theory. 

I think we have EJ Screen. We have SLD under built environment. 

There are few datasets that frustratingly defy classification in one.

**Comment by d-wasserman** [comment]
Recent commit addresses this.
