### ISSUE TITLE
Sponsorship PDF

### ISSUE THREAD

**Issue by d-wasserman** [APA-Technology-Division/urban-and-regional-planning-resources#82]
@lianplass - what do you think about adding the sponsorship pdf in a "sponsoring" folder? Thoughts?

**Comment by lianplass** [comment]
Okay--moving the file location will break links on two pages I think.  I'll update after the move.

**Comment by d-wasserman** [comment]
I don't want us to break any existing links, just add the sponsorship PDF in the resources folder. 
https://github.com/APA-Technology-Division/urban-and-regional-planning-resources/tree/main/resources
We can link to it in the sponsor introduction section.

**Comment by lianplass** [comment]
Oh!  I misunderstood.  The file also lives in the Division's Github Pages, is all: 
https://apa-technology-division.github.io/assets/Division_Sponsorship_Package_22.pdf
I can add it to that repo folder as well.

**Comment by d-wasserman** [comment]
We can just link to this in the sponsorship area as a hyperlink. We don't
need to add to the repo then.
David Wasserman
Email: ***@***.***
Cell: 407 325 6242

**Comment by d-wasserman** [comment]
I see it in the folder. I will make a minor edit.
David Wasserman
Email: ***@***.***
Cell: 407 325 6242

**Comment by d-wasserman** [comment]
This should be a relative link (https://github.com/APA-Technology-Division/urban-and-regional-planning-resources/commit/263e9d43892b4d3366a4047165a85bf14b1c406a), but this works for now. Closing the issue for the time being.
