### ISSUE TITLE
OpenPrecincts Redirects to Spam. Alternatives

### ISSUE THREAD

**Issue by ArmanMadani** [APA-Technology-Division/urban-and-regional-planning-resources#87]
OpenPrecincts[dot]org is no longer maintained by the Princeton gerrymandering research group. The site redirects to spam (I don't recommend clicking the link in the Readme). It should be replaced by the following: 
- https://gerrymander.princeton.edu/
- https://redistrictingdatahub.org/ (the group seemed to think they still owned and redirected OpenPrecincts to this URL)

**Comment by d-wasserman** [comment]
Spam redirects is definitely not something our link checker does on commit, so thank you for reporting this.

**Comment by d-wasserman** [comment]
Addresesd by https://github.com/APA-Technology-Division/urban-and-regional-planning-resources/commit/59288ea6dbe8cf3adaa8ef10e5bc8e425511fd30
