### ISSUE TITLE
Running Thread for Heat Data/Tools/Resources

### ISSUE THREAD

**Issue by lianplass** [APA-Technology-Division/urban-and-regional-planning-resources#90]
Hi All,

Just wanted to follow up on the board's earlier conversations about adding more heat-related resources to the repo.  I need to go through my saved content and pull up what I have but for now, I'm opening an issue for it so we can aggregate and discuss before a commit/merge

-Li

**Comment by d-wasserman** [comment]
Added them in from your last pull request. Had to fix some duplicates, but identified another issue so thanks!
